# Generated by Django 4.0.1 on 2022-06-09 13:20

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesavaari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='country',
            field=django_countries.fields.CountryField(default='India', max_length=2),
        ),
        migrations.AddField(
            model_name='agent',
            name='pincode',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='corporatecust',
            name='country',
            field=django_countries.fields.CountryField(default='India', max_length=2),
        ),
        migrations.AddField(
            model_name='corporatecust',
            name='pincode',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=django_countries.fields.CountryField(default='India', max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AlterField(
            model_name='agent',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='corporatecust',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
